---
- hosts: hadoop
  remote_user: root
  gather_facts: no
  roles:
    - prepare
  tags: prepare

- hosts: hadoop
  remote_user: hdp
  gather_facts: no
  roles:
    - install
  tags: install

- hosts: localhost
  remote_user: hdp
  roles:
    - inialconf
  tags: inialconf

- hosts: hadoop
  remote_user: hdp
  gather_facts: no
  roles:
    - setupenv
  tags: setupenv

