---
- name: copy ssh key
  include: ssh-addkey.yml

- name: generate soft folder
  file: 
    mode: 0764
    path: /home/hdp/soft
    state: directory
    force: yes
- name: download hadoop
  command: wget http://www-eu.apache.org/dist/hadoop/common/hadoop-2.8.2/hadoop-2.8.2.tar.gz
  args:
    chdir: /home/hdp/soft
    creates: hadoop-2.8.2.tar.gz
  register: output_hadoop
- name: download hive
  command: wget http://www-eu.apache.org/dist/hive/hive-1.2.2/apache-hive-1.2.2-bin.tar.gz
  args:
    chdir: /home/hdp/soft
    creates: apache-hive-1.2.2-bin.tar.gz
  register: output_hive
- name: download hbase
  command: wget http://www-eu.apache.org/dist/hbase/1.3.1/hbase-1.3.1-bin.tar.gz
  args:
    chdir: /home/hdp/soft
    creates: hbase-1.3.1-bin.tar.gz
  register: output_hbase

- debug: var="{{ output_hadoop.stdout}}"
- debug: var="{{ output_hive.stdout}}"
- debug: var="{{ output_hbase.stdout}}"
  
- name: uncompress tar files - hadoop
  command: tar -xzvf hadoop-2.8.2.tar.gz -C ..
  args:
    chdir: /home/hdp/soft
  when: output_hadoop.stdout.find('skip') == -1
  ignore_errors: yes 

- name: uncompress tar files - hive
  command: tar -xzvf apache-hive-1.2.2-bin.tar.gz -C ..
  args:
    chdir: /home/hdp/soft
  when: output_hive.stdout.find('skip') == -1
  ignore_errors: yes

- name: uncompress tar files - hbase
  command: tar -xzvf hbase-1.3.1-bin.tar.gz -C ..
  args:
    chdir: /home/hdp/soft
  when: output_hbase.stdout.find('skip') == -1
  ignore_errors: yes
